include_list:
  - Human immunodeficiency virus 1
  - Human immunodeficiency virus 2
  - Simian immunodeficiency virus
db_path: <base_path>
gb_file_prefix: gbvrl
exclude_list:
  - Severe acute respiratory syndrome coronavirus 2
date: "<genbank release date>"
